
from typing import Protocol, Dict, Any, Iterable
class EdgeAdapter(Protocol):
    def configure(self, cfg: Dict[str, Any]) -> None: ...
    def source(self) -> Iterable[Dict[str, Any]]: ...
    def preprocess(self, item: Dict[str, Any]) -> Dict[str, Any]: ...
    def to_slice(self, item: Dict[str, Any]) -> Dict[str, Any]: ...
    def healthcheck(self) -> Dict[str, Any]: ...
